### ISSUE TITLE
大神这本书写的很好，是我看过的spark方面最好的书了。有没有写一本flink书的计划呢？？？

### ISSUE THREAD

**Issue by zdkzdk** [JerryLead/ApacheSparkBook#17]
flink我初步了解了下，好像比spark先进，至少容错上更先进一点，他们用分布式快照

**Comment by JerryLead** [comment]
非大神，只是大数据处理框架的研究人员，多谢关注。目前我的主要精力在研究新的东西、撰写论文等，虽然也有部分涉及到Flink，但没有足够的精力去完成一部高质量的著作，所以目前还没有写作计划。

**Comment by zdkzdk** [comment]
好的，期待您的下一部著作

**Comment by zdkzdk** [comment]
close
