### ISSUE TITLE
是不是看了这本书，就不用再看您的spark internals文档了？？？

### ISSUE THREAD

**Issue by zdkzdk** [JerryLead/ApacheSparkBook#18]

**Comment by JerryLead** [comment]
这本书的写作目的是从实践经验中抽象出理论，并以Spark为主去解释理论。SparkInternasl包含了本书中的部分理论，以及本书中没有涉及的一些具体代码解析（虽然版本有点老）。可以结合看，也可以“本书+最新代码”看。
